### ISSUE TITLE
ZeroDivisionError at role%

### ISSUE THREAD

**Issue by c0derMo** [c0derMo/clash-team-analyzer#1]
Tool encounters an error when matchlist of a player is empty.

```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sanic/app.py", line 942, in handle_request
    response = await response
  File "./main.py", line 65, in getTeam
    mightBeHTML = util.exportStringHTML(playerOBJs)
  File "/cta/util.py", line 89, in exportStringHTML
    line = line.replace("%P" + str(index) + "-TOP", str(round(player.getToplanePercent(), 1)))
  File "/cta/Player.py", line 55, in getToplanePercent
    return (topmatches / self.matchlist["matches"].__len__()) * 100
ZeroDivisionError: division by zero

**Comment by c0derMo** [comment]
Additional information after reproducing:
Player has no matches in the last 30d, therefore `self.matchlist` is empty.
**This is not related to anything else**
